### ISSUE TITLE
Tasks and To-Do List

### ISSUE THREAD

**Issue by pedroka-dev** [pedro-ca/Parking-Lot-Control#1]
- [x] Specify initial tasks and scopes
- [x] Write an introduction
- [x] Update tasks to current classes name
- [x] Update tasks to implement entries and exit

---
- [x] **Layer "model.bo"** - classes and their attributes
  - [x] Proper abstraction and connectivity of all classes
  - [x] Clear out useless and redundant class attributes
  - [x] "CarBrand" 
  - [x] "CarModel"
  - [x] "CarVersion" 
  - [x] "Vehicle"
  - [x] "Entry"
  - [x] "Exit"
  - [x] "Person"
  - [x] "Person"
  - [x] Include Id Attribute

---
- [x] **Layer "model.DAOSer"**
  - [x] "Serialize" - main method for serialization and deseralization
  - [x] "InterfaceDAOSer" 
  - [x] "CarBrandDAOSer" 
  - [x] "CarModelDAOSer"
  - [x] "CarVersiolDAOSer" 
  - [x] "VehicleDAOSer"
  - [x] "EntryDAOSer"
  - [x] "ExitDAOSer"
  - [x] "PersonDAOSer"

---

- [x] **Layer "view"** - Layout GUI
  - [x] "MainMenuView"
  - [x] Update var and class names to english
  - [x] CarBrand
    - [x] "ListCarBrandView"
    - [x] "RegCarBrandView"
  - [x] CarModel
    - [x] "ListCarModelView"
    - [x] "RegCarModelView"
  - [x] CarVersion
    - [x] "ListCarVersionView"
    - [x] "RegCarVersionView"
  - [x] Vehicle
    - [x] "ListVehicleView"
    - [x] "RegVehicleView"
  - [x] Person
    - [x] "ListPersonView"
    - [x] "RegPersonView"
  - [x] Entry and exits
---
- [x] **Layer "controller"**
  - [x] Add functionality for the ListsXControls
    - [x] JTable
    - [ ] "Edit" button 
    - [ ] "Delete" 
  - [x] Add functionality for the RegXControls
  - [x] Fix possible ParseInt errors on RegXControls
  - [x] CarBrand
    - [x] "ListCarBrandControl"
    - [x] "RegCarBrandControl"
  - [x] CarModel
    - [x] "ListCarModelControl"
    - [x] "RegCarModelControl"
  - [x] CarVersion
    - [x] "ListCarVersionControl"
    - [x] "RegCarVersionControl"
  - [x] Vehicle
    - [x] "ListVehicleControl"
    - [x] "RegVehicleControl"
  - [x] Person
    - [x] "ListPersonControl"
    - [x] "RegPersonControl"

---
- [x] **Layer "service"**
  - [x] "CarBrandService" 
  - [x] "CarModelService"
  - [x] "CarVersionService" 
  - [x] "VehicleService"
  - [x] "EntryService"
  - [x] "ExitService"
  - [x] "PersonService"
